%CENSUS_TRANSFORM

% Copyright Snap Inc. 2020
% This sample code is made available by Snap Inc. for informational
% purposes only.  It is provided as-is, without warranty of any kind,
% express or implied, including any warranties of merchantability, fitness
% for a particular purpose, or non-infringement.  In no event will Snap
% Inc. be liable for any damages arising from the sample code or your use
% thereof.

function B = census_transform(A)
B = cat(3, A < A([1 1:end-1],:,:), ...
           A < A([1 1:end-1],[1 1:end-1],:), ...
           A < A(:,[1 1:end-1],:), ...
           A < A([2:end end],:,:), ...
           A < A(:,[2:end end],:), ...
           A < A([2:end end],[2:end end],:), ...
           A < A([1 1:end-1],[2:end end],:), ...
           A < A([2:end end],[1 1:end-1],:));
end